on:
  push:
    branches:
      - DevHans1
jobs:
  verify_spec:
    runs-on: self-hosted
    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Setup inso
      uses: kong/setup-inso@v1
      with:
        inso-version: 3.5.0
    - name: Verify inso version
      run: inso --version
    - name: Lint
      run: inso lint spec "stock_api.yaml" --ci
    - name: Run test suite 1
      run: inso run test "200 Tests" --env "Kong EMEA ProxyDemo" --ci
    - name: Run test suite 2
      run: inso run test "Data Type Tests Suite" --env "Kong EMEA ProxyDemo" --ci
    - name: Generate declarative config
      run: inso generate config "stock_api.yaml" --type declarative --ci
